#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
background = 'transparent'
foreground = 'p:pink'
template = '{{ .Path }}'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = 'p:blue'
background = 'transparent'
template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

[blocks.segments.properties]
branch_icon = ' '
commit_icon = '@ '
cherry_pick_icon = ' '
merge_icon = ' '
rebase_icon = ' '
revert_icon = ' '
tag_icon = ' '
fetch_status = true

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
background = 'transparent'
foreground = 'p:red'
template = '{{ .FormattedMs }}'

[blocks.segments.properties]
threshold = 3000

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
background = 'transparent'
foreground = 'p:os'
template = '❯ '

# CATPPUCCIN theme palette
[palette]
blue = '#89B4FA'
sky = '#89DCEB'
pink = '#F5C2E7'
red = '#F38BA8'
green = '#A6E3A1'
text = '#CDD6F4'
